/** @format */

import { definePrivateEventHandler } from "../../..";
import { PrismaClient } from "@prisma/client";
import prisma from "../../../../prisma/my_prisma";

export default definePrivateEventHandler(
  async (event, user) => {
    let departments = [];
    try {
      return [
        "Afghanistan",
        "Afrique du Sud",
        "Albanie",
        "Algérie",
        "Allemagne",
        "Andorre",
        "Angola",
        "Anguilla",
        "Antigua-et-Barbuda",
        "Arabie saoudite",
        "Argentine",
        "Arménie",
        "Aruba",
        "Australie",
        "Autriche",
        "Azerbaïdjan",
        "Bahamas",
        "Bahreïn",
        "Bangladesh",
        "Barbade",
        "Belgique",
        "Belize",
        "Bermudes",
        "Bhoutan",
        "Bolivie (État plurinational de)",
        "Bonaire, Saint-Eustache et Saba",
        "Bosnie-Herzégovine",
        "Botswana",
        "Brunéi Darussalam",
        "Brésil",
        "Bulgarie",
        "Burkina Faso",
        "Burundi",
        "Bélarus",
        "Bénin",
        "Cambodge",
        "Cameroun",
        "Canada",
        "Cap-Vert",
        "Chili",
        "Chine",
        "Chypre",
        "Colombie",
        "Comores",
        "Congo",
        "Corée (République populaire démocratique de)",
        "Costa Rica",
        "Croatie",
        "Cuba",
        "Curaçao",
        "Côte d'Ivoire",
        "Danemark",
        "Djibouti",
        "Dominique",
        "El Salvador",
        "Espagne",
        "Estonie",
        "Fidji",
        "Finlande",
        "France",
        "Fédération de Russie",
        "Gabon",
        "Gambie",
        "Ghana",
        "Gibraltar",
        "Grenade",
        "Groenland",
        "Grèce",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernesey",
        "Guinée",
        "Guinée équatoriale",
        "Guinée-Bissau",
        "Guyana",
        "Guyane française",
        "Géorgie",
        "Géorgie du Sud et les îles Sandwich du Sud",
        "Honduras",
        "Hong Kong",
        "Hongrie",
        "Inde",
        "Indonésie",
        "Irak",
        "Iran (République islamique d')",
        "Irlande",
        "Islande",
        "Israël",
        "Italie",
        "Jamaïque",
        "Japon",
        "Jersey",
        "Jordanie",
        "Kazakhstan",
        "Kenya",
        "Kirghizistan",
        "Kiribati",
        "Koweït",
        "Lesotho",
        "Lettonie",
        "Liban",
        "Libye",
        "Libéria",
        "Liechtenstein",
        "Lituanie",
        "Luxembourg",
        "Macao",
        "Macédoine du Nord",
        "Madagascar",
        "Malaisie",
        "Malawi",
        "Maldives",
        "Mali",
        "Malte",
        "Maroc",
        "Maurice",
        "Mauritanie",
        "Mayotte",
        "Mexique",
        "Micronésie (États fédérés de)",
        "Moldavie (République de)",
        "Monaco",
        "Mongolie",
        "Montserrat",
        "Monténégro",
        "Mozambique",
        "Myanmar",
        "Namibie",
        "Nauru",
        "Nicaragua",
        "Niger",
        "Nigéria",
        "Niué",
        "Norvège",
        "Nouvelle-Calédonie",
        "Nouvelle-Zélande",
        "Népal",
        "Oman",
        "Ouganda",
        "Ouzbékistan",
        "Ouzbékistan",
        "Pakistan",
        "Palaos",
        "Palestine, État de",
        "Panama",
        "Papouasie-Nouvelle-Guinée",
        "Paraguay",
        "Pays-Bas",
        "Philippines",
        "Pitcairn",
        "Pologne",
        "Polynésie française",
        "Porto Rico",
        "Portugal",
        "Pérou",
        "Qatar",
        "Roumanie",
        "Royaume-Uni",
        "Royaume-Uni",
        "Rwanda",
        "République arabe syrienne",
        "République centrafricaine",
        "République dominicaine",
        "République du Kosovo",
        "République démocratique du Congo",
        "République démocratique populaire lao",
        "République tchèque",
        "République-Unie de Tanzanie",
        "Réunion",
        "Sahara occidental",
        "Saint-Barthélemy",
        "Saint-Kitts-et-Nevis",
        "Saint-Marin",
        "Saint-Martin (partie française)",
        "Saint-Pierre-et-Miquelon",
        "Saint-Siège",
        "Saint-Vincent-et-les Grenadines",
        "Sainte-Hélène, Ascension et Tristan da Cunha",
        "Sainte-Lucie",
        "Samoa",
        "Samoa américaines",
        "Sao Tomé-et-Principe",
        "Serbie",
        "Seychelles",
        "Sierra Leone",
        "Singapour",
        "Slovaquie",
        "Slovénie",
        "Somalie",
        "Soudan",
        "Sri Lanka",
        "Suisse",
        "Suriname",
        "Suède",
        "Sénégal",
        "Tadjikistan",
        "Taïwan",
        "Tchad",
        "Terres australes françaises",
        "Territoire britannique de l'océan Indien",
        "Thaïlande",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinité-et-Tobago",
        "Tunisie",
        "Turkménistan",
        "Turquie",
        "Tuvalu",
        "Ukraine",
        "Ukraine",
        "Uruguay",
        "Uruguay",
        "Vanuatu",
        "Vanuatu",
        "Venezuela (République bolivarienne du)",
        "Venezuela (République bolivarienne du)",
        "Viêt Nam",
        "Viêt Nam",
        "Wallis-et-Futuna",
        "Wallis-et-Futuna",
        "Yémen",
        "Zambie",
        "Zimbabwe",
        "Égypte",
        "Émirats arabes unis",
        "Émirats arabes unis",
        "Équateur",
        "Érythrée",
        "États-Unis d'Amérique",
        "États-Unis d'Amérique",
        "Éthiopie",
        "Île Bouvet",
        "Île Christmas",
        "Île Norfolk",
        "Île de Man",
        "Îles Caïmans",
        "Îles Cocos (Keeling)",
        "Îles Cook",
        "Îles Féroé",
        "Îles Malouines (Falkland)",
        "Îles Mariannes du Nord",
        "Îles Marshall",
        "Îles Salomon",
        "Îles Turques et Caïques",
        "Îles Vierges britanniques",
        "Îles Vierges des États-Unis",
        "Îles mineures éloignées des États-Unis",
        "Îles Åland",
      ];
    } catch (error) {
      console.error(error);
      throw createError({
        statusCode: 400,
        message: "Un problème est survenue.",
      });
    }
  },
  { auth: false }
);
